# Generated by Django 3.0 on 2019-12-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='cns_medico',
            field=models.CharField(default='CNS do médico', max_length=200),
        ),
        migrations.AddField(
            model_name='medico',
            name='crm',
            field=models.CharField(default='CRM do médico', max_length=200),
        ),
        migrations.AddField(
            model_name='medico',
            name='nome',
            field=models.CharField(default='Nome completo do médico', max_length=200),
        ),
    ]
