# Generated by Django 3.0 on 2019-12-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_auto_20191208_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='cns_medico',
        ),
        migrations.AddField(
            model_name='medico',
            name='cns',
            field=models.CharField(default='CNS do médico', max_length=10),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(default='CRM do médico', max_length=10),
        ),
    ]
