# Generated by Django 3.0 on 2019-12-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_auto_20191209_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='cns',
            field=models.CharField(default='CNS do médico', max_length=17),
        ),
    ]
