# Generated by Django 5.2.4 on 2025-07-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_alter_medico_id_alter_medicousuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='cns_medico',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm_medico',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
