# Generated by Django 3.0.1 on 2020-01-29 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicos', '0003_auto_20200106_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='usuario',
        ),
        migrations.CreateModel(
            name='MedicoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicos.Medico')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='usuarios',
            field=models.ManyToManyField(related_name='medicos', through='medicos.MedicoUsuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
