# Generated by Django 5.2.4 on 2025-07-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_alter_medico_cns_medico_alter_medico_crm_medico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(blank=True, choices=[('ALERGIA_IMUNOLOGIA', 'Alergia e Imunologia'), ('ANESTESIOLOGIA', 'Anestesiologia'), ('ANGIOLOGIA', 'Angiologia'), ('CARDIOLOGIA', 'Cardiologia'), ('CIRURGIA_CARDIOVASCULAR', 'Cirurgia Cardiovascular'), ('CIRURGIA_MAO', 'Cirurgia da Mão'), ('CIRURGIA_CABECA_PESCOCO', 'Cirurgia de Cabeça e Pescoço'), ('CIRURGIA_APARELHO_DIGESTIVO', 'Cirurgia do Aparelho Digestivo'), ('CIRURGIA_GERAL', 'Cirurgia Geral'), ('CIRURGIA_PEDIATRICA', 'Cirurgia Pediátrica'), ('CIRURGIA_PLASTICA', 'Cirurgia Plástica'), ('CIRURGIA_TORACICA', 'Cirurgia Torácica'), ('CIRURGIA_VASCULAR', 'Cirurgia Vascular'), ('CLINICA_MEDICA', 'Clínica Médica'), ('COLOPROCTOLOGIA', 'Coloproctologia'), ('DERMATOLOGIA', 'Dermatologia'), ('ENDOCRINOLOGIA', 'Endocrinologia e Metabologia'), ('ENDOSCOPIA', 'Endoscopia'), ('GASTROENTEROLOGIA', 'Gastroenterologia'), ('GENETICA_MEDICA', 'Genética Médica'), ('GERIATRIA', 'Geriatria'), ('GINECOLOGIA_OBSTETRICIA', 'Ginecologia e Obstetrícia'), ('HEMATOLOGIA', 'Hematologia e Hemoterapia'), ('HOMEOPATIA', 'Homeopatia'), ('INFECTOLOGIA', 'Infectologia'), ('MASTOLOGIA', 'Mastologia'), ('MEDICINA_FAMILIA', 'Medicina de Família e Comunidade'), ('MEDICINA_EMERGENCIA', 'Medicina de Emergência'), ('MEDICINA_TRABALHO', 'Medicina do Trabalho'), ('MEDICINA_TRAFEGO', 'Medicina do Tráfego'), ('MEDICINA_ESPORTIVA', 'Medicina Esportiva'), ('MEDICINA_FISICA_REABILITACAO', 'Medicina Física e Reabilitação'), ('MEDICINA_INTENSIVA', 'Medicina Intensiva'), ('MEDICINA_LEGAL', 'Medicina Legal e Perícia Médica'), ('MEDICINA_NUCLEAR', 'Medicina Nuclear'), ('MEDICINA_PREVENTIVA', 'Medicina Preventiva e Social'), ('NEFROLOGIA', 'Nefrologia'), ('NEUROCIRURGIA', 'Neurocirurgia'), ('NEUROLOGIA', 'Neurologia'), ('NUTROLOGIA', 'Nutrologia'), ('OBSTETRICIA', 'Obstetrícia'), ('OFTALMOLOGIA', 'Oftalmologia'), ('ORTOPEDIA_TRAUMATOLOGIA', 'Ortopedia e Traumatologia'), ('OTORRINOLARINGOLOGIA', 'Otorrinolaringologia'), ('PATOLOGIA', 'Patologia'), ('PATOLOGIA_CLINICA', 'Patologia Clínica/Medicina Laboratorial'), ('PEDIATRIA', 'Pediatria'), ('PNEUMOLOGIA', 'Pneumologia'), ('PSIQUIATRIA', 'Psiquiatria'), ('RADIOLOGIA', 'Radiologia e Diagnóstico por Imagem'), ('RADIOTERAPIA', 'Radioterapia'), ('REUMATOLOGIA', 'Reumatologia'), ('TOXICOLOGIA', 'Toxicologia Médica'), ('UROLOGIA', 'Urologia'), ('OUTRA', 'Outra')], max_length=50, null=True, verbose_name='Especialidade Médica'),
        ),
        migrations.AddField(
            model_name='medico',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado do CRM'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm_medico',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='medico',
            unique_together={('crm_medico', 'estado')},
        ),
    ]
