# Generated by Django 5.2.4 on 2025-07-26 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicos", "0005_alter_medico_options_medico_especialidade_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="medicousuario",
            index=models.Index(fields=["usuario"], name="medicousuario_usuario_idx"),
        ),
        migrations.AddIndex(
            model_name="medicousuario",
            index=models.Index(fields=["medico"], name="medicousuario_medico_idx"),
        ),
    ]
