version: '3.7'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: gunicorn autocusto.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/autocusto/
      - static_volume:/usr/src/autocusto/static/
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/usr/src/autocusto/static/
    depends_on:
      - web
      
volumes:
  static_volume: 


