version: '3.7'

services:
  autocusto:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: gunicorn autocusto.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/autocusto/
      - static_volume:/home/autocusto/autocusto/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/autocusto/autocusto/static
    depends_on:
      - autocusto
      
volumes:
  static_volume: 

