version: '3.7'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: gunicorn autocusto.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/autocusto/
      - static_volume:/usr/src/autocusto/static/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db  
  db:
    image: postgres:12-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lucas
      - POSTGRES_PASSWORD=rraptnor
      - POSTGRES_DB=autocusto
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/usr/src/autocusto/static/
    depends_on:
      - web
      
volumes:
  static_volume:
  postgres_data: 


