services:
  db:
    image: postgres:17.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lucas
      - POSTGRES_PASSWORD=rraptnor
      - POSTGRES_DB=autocusto
    ports:
      - "5432:5432"
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/home/appuser/app
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
      - /dev/shm:rw,noexec,nosuid,size=100m
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=jklahjkldfakjhKLJHADJKFHASDKHFJKLhadsfhjkladhOIUYHQ6516AS5DFASD65F48A6S1652asd1f3as2d
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0
      - USE_X_FORWARDED_HOST=1
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=autocusto
      - SQL_USER=lucas
      - SQL_PASSWORD=rraptnor
      - SQL_HOST=db
      - SQL_PORT=5432

  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - ./static_root:/home/appuser/app/static_root
    depends_on:
      - web

volumes:
  postgres_data: