# Generated by Django 3.0 on 2019-12-12 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('idade', models.CharField(max_length=100, null=True)),
                ('sexo', models.CharField(max_length=100, null=True)),
                ('nome_mae', models.CharField(max_length=100, null=True)),
                ('incapaz', models.BooleanField(null=True)),
                ('nome_responsavel', models.CharField(max_length=100, null=True)),
                ('rg', models.CharField(max_length=100, null=True)),
                ('peso', models.CharField(max_length=100, null=True)),
                ('altura', models.CharField(default='1,70m', max_length=100)),
                ('escolha_etnia', models.CharField(max_length=100, null=True)),
                ('cpf_paciente', models.CharField(max_length=100, null=True)),
                ('cns_paciente', models.CharField(max_length=100, null=True)),
                ('email_paciente', models.EmailField(max_length=254, null=True)),
                ('cidade_paciente', models.CharField(max_length=100, null=True)),
                ('end_paciente', models.CharField(max_length=100, null=True)),
                ('cep_paciente', models.CharField(max_length=100, null=True)),
                ('telefone1_paciente', models.CharField(max_length=100, null=True)),
                ('telefone2_paciente', models.CharField(max_length=100, null=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
