# Generated by Django 3.0 on 2019-12-17 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        ('clinicas', '0002_clinica_medicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=100)),
                ('incapaz', models.BooleanField()),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('altura', models.CharField(default='1,70m', max_length=100)),
                ('escolha_etnia', models.CharField(max_length=100)),
                ('cpf_paciente', models.CharField(max_length=100, unique=True)),
                ('cns_paciente', models.CharField(max_length=100)),
                ('email_paciente', models.EmailField(max_length=254, null=True)),
                ('cidade_paciente', models.CharField(max_length=100)),
                ('end_paciente', models.CharField(max_length=100)),
                ('cep_paciente', models.CharField(max_length=100)),
                ('telefone1_paciente', models.CharField(max_length=100)),
                ('telefone2_paciente', models.CharField(max_length=100)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicas.Clinica')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.Medico')),
            ],
        ),
    ]
