# Generated by Django 3.0 on 2019-12-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cns_paciente',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
