# Generated by Django 3.0 on 2020-01-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='etnia',
            field=models.CharField(default='indefinido', max_length=10),
            preserve_default=False,
        ),
    ]
