# Generated by Django 3.0 on 2019-12-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_auto_20191209_1337'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='altura',
            field=models.CharField(default='1,70m', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cep_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cidade_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cns_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email_paciente',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='end_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='escolha_etnia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='idade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='incapaz',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicos.Medico'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_responsavel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone1_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone2_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
