# Generated by Django 3.0 on 2019-12-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='clinica',
        ),
    ]
