# Generated by Django 5.2.4 on 2025-07-25 03:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=100)),
                ('incapaz', models.BooleanField()),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('altura', models.CharField(default='1,70m', max_length=100)),
                ('escolha_etnia', models.CharField(max_length=100)),
                ('cns_paciente', models.CharField(max_length=100)),
                ('email_paciente', models.EmailField(blank=True, max_length=254, null=True)),
                ('cidade_paciente', models.CharField(max_length=100)),
                ('end_paciente', models.CharField(max_length=100)),
                ('cep_paciente', models.CharField(max_length=100)),
                ('telefone1_paciente', models.CharField(max_length=100)),
                ('telefone2_paciente', models.CharField(max_length=100)),
                ('etnia', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version_number', models.IntegerField()),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes in this version')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('archived', 'Arquivado')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_versions_created', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Versão do Paciente',
                'verbose_name_plural': 'Versões dos Pacientes',
                'ordering': ['-version_number', '-created_at'],
                'unique_together': {('paciente', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='PacienteUsuarioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paciente_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_version', to='pacientes.paciente_usuarios')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='pacientes.pacienteversion')),
            ],
            options={
                'verbose_name': 'Versão Ativa do Usuário (Paciente)',
                'verbose_name_plural': 'Versões Ativas dos Usuários (Pacientes)',
            },
        ),
    ]
