# Generated by Django 3.0 on 2020-01-27 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0003_paciente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.ManyToManyField(related_name='pacientes', to=settings.AUTH_USER_MODEL),
        ),
    ]
