# Generated by Django 3.0 on 2019-12-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20191219_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cns_paciente',
            field=models.CharField(max_length=100),
        ),
    ]
