# Generated by Django 3.0 on 2020-01-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20200127_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='usuario',
            new_name='usuarios',
        ),
    ]
