# Generated by Django 5.2.4 on 2025-07-25 03:36

from django.db import migrations


def create_initial_patient_versions(apps, schema_editor):
    """
    Create initial versions for all existing patient-user relationships.
    
    For each patient-user relationship that doesn't have a PacienteUsuarioVersion,
    create an initial version using the master patient data.
    """
    Paciente = apps.get_model('pacientes', 'Paciente')
    PacienteVersion = apps.get_model('pacientes', 'PacienteVersion')
    PacienteUsuarioVersion = apps.get_model('pacientes', 'PacienteUsuarioVersion')
    
    # Get the through model for Paciente.usuarios relationship
    PacienteUsuarios = Paciente.usuarios.through
    
    # Find all patient-user relationships that don't have a version assigned
    patient_users_without_versions = PacienteUsuarios.objects.filter(
        active_version__isnull=True
    ).select_related('paciente', 'usuario')
    
    print(f"Found {patient_users_without_versions.count()} patient-user relationships without versions")
    
    for patient_user in patient_users_without_versions:
        paciente = patient_user.paciente
        usuario = patient_user.usuario
        
        if not paciente or not usuario:
            continue
            
        # Check if this patient already has versions
        existing_version = PacienteVersion.objects.filter(paciente=paciente).first()
        
        if existing_version:
            # Patient already has versions, assign the latest active one to this user
            latest_version = PacienteVersion.objects.filter(
                paciente=paciente,
                status='active'
            ).order_by('-version_number').first()
            
            if latest_version:
                PacienteUsuarioVersion.objects.create(
                    paciente_usuario=patient_user,
                    version=latest_version
                )
                print(f"Assigned existing version {latest_version.version_number} to user {usuario.email} for patient {paciente.nome_paciente}")
        else:
            # Patient has no versions yet, create initial version from master data
            initial_version = PacienteVersion.objects.create(
                paciente=paciente,
                version_number=1,
                created_by=usuario,
                status='active',
                nome_paciente=paciente.nome_paciente,
                idade=paciente.idade,
                sexo=paciente.sexo,
                nome_mae=paciente.nome_mae,
                incapaz=paciente.incapaz,
                nome_responsavel=paciente.nome_responsavel,
                rg=paciente.rg,
                peso=paciente.peso,
                altura=paciente.altura,
                escolha_etnia=paciente.escolha_etnia,
                cns_paciente=paciente.cns_paciente,
                email_paciente=paciente.email_paciente,
                cidade_paciente=paciente.cidade_paciente,
                end_paciente=paciente.end_paciente,
                cep_paciente=paciente.cep_paciente,
                telefone1_paciente=paciente.telefone1_paciente,
                telefone2_paciente=paciente.telefone2_paciente,
                etnia=paciente.etnia,
                change_summary='Versão inicial criada durante migração'
            )
            
            # Assign this version to the user
            PacienteUsuarioVersion.objects.create(
                paciente_usuario=patient_user,
                version=initial_version
            )
            print(f"Created initial version for user {usuario.email} for patient {paciente.nome_paciente}")


def reverse_initial_patient_versions(apps, schema_editor):
    """
    Remove all PacienteUsuarioVersion relationships created by this migration.
    """
    PacienteUsuarioVersion = apps.get_model('pacientes', 'PacienteUsuarioVersion')
    PacienteVersion = apps.get_model('pacientes', 'PacienteVersion')
    
    # Remove version assignments
    PacienteUsuarioVersion.objects.all().delete()
    
    # Remove versions created during migration (those with change_summary containing 'migração')
    PacienteVersion.objects.filter(
        change_summary__icontains='migração'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_pacienteversion_pacienteusuarioversion'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_patient_versions,
            reverse_initial_patient_versions
        ),
    ]
