# Generated by Django 3.0 on 2020-02-02 21:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('clinicas', '0002_emissor_medico'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anamnese', models.TextField(max_length=600)),
                ('cid', models.CharField(max_length=6)),
                ('diagnostico', models.CharField(max_length=200)),
                ('medicamento1', django.contrib.postgres.fields.jsonb.JSONField()),
                ('med2', django.contrib.postgres.fields.jsonb.JSONField()),
                ('med3', django.contrib.postgres.fields.jsonb.JSONField()),
                ('med4', django.contrib.postgres.fields.jsonb.JSONField()),
                ('med5', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tratou', models.BooleanField(default=False)),
                ('tratamentos_previos', models.TextField(max_length=600)),
                ('data1', models.DateField(null=True)),
                ('preenchido_por', models.CharField(choices=[('P', 'Paciente'), ('M', 'Mãe'), ('R', 'Responsável'), ('M', 'Médico')], max_length=128)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='clinicas.Clinica')),
                ('emissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='clinicas.Emissor')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='medicos.Medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='pacientes.Paciente')),
            ],
        ),
    ]
