# Generated by Django 3.0 on 2020-02-23 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doenca',
            name='protocolo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doenca', to='processos.Protocolo'),
        ),
    ]
