# Generated by Django 3.0 on 2019-12-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='posologia_med1',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
