# Generated by Django 3.0 on 2019-12-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='data2',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='data3',
        ),
    ]
