# Generated by Django 3.0 on 2020-02-03 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20200203_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doenca',
            name='protocolo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processos.Protocolo'),
        ),
    ]
