# Generated by Django 3.0 on 2019-12-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_processo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='clinica',
        ),
    ]
