# Generated by Django 3.0 on 2020-02-04 00:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20200204_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='apresentacoes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=600), size=None),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(max_length=600, unique=True),
        ),
    ]
