# Generated by Django 3.0 on 2019-12-20 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20191219_2302'),
        ('processos', '0002_auto_20191219_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='pacientes.Paciente'),
        ),
    ]
