# Generated by Django 3.0 on 2020-02-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20200225_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(max_length=600),
        ),
    ]
