# Generated by Django 3.0 on 2019-12-20 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0005_emissor_pacientes'),
        ('medicos', '0002_medico_usuario'),
        ('processos', '0003_auto_20191220_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinicas', to='clinicas.Clinica'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='emissor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissor', to='clinicas.Emissor'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='medicos.Medico'),
        ),
    ]
