# Generated by Django 3.0 on 2020-02-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_auto_20200204_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='arquivo',
            field=models.CharField(default='nome_arquivo', max_length=300),
            preserve_default=False,
        ),
    ]
