# Generated by Django 5.2rc1 on 2025-07-16 12:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_id'),
        ('processos', '0003_alter_doenca_id_alter_medicamento_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processo',
            unique_together={('usuario', 'paciente', 'doenca')},
        ),
    ]
