# Generated by Django 3.0 on 2019-12-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_remove_paciente_clinica'),
        ('processos', '0003_remove_processo_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='pacientes.Paciente'),
        ),
    ]
