# Generated by Django 3.0 on 2020-01-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_auto_20200112_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='med1_via',
            field=models.CharField(default='oral', max_length=100),
            preserve_default=False,
        ),
    ]
