# Generated by Django 5.2.4 on 2025-07-28 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0004_alter_processo_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="processo",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="processo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
