# Generated by Django 3.0 on 2020-02-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_protocolo_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='arquivo',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='nome',
            field=models.CharField(max_length=600),
        ),
    ]
