# Generated by Django 3.0 on 2019-12-20 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0005_emissor_pacientes'),
        ('processos', '0005_auto_20191220_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='emissor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugigangas', to='clinicas.Emissor'),
        ),
    ]
