# Generated by Django 3.0 on 2020-02-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_auto_20200206_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doenca',
            name='protocolo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doenca', to='processos.Protocolo'),
        ),
    ]
