# Generated by Django 3.0 on 2019-12-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0005_emissor_pacientes'),
        ('processos', '0006_auto_20191220_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='emissor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicas.Emissor'),
        ),
    ]
