
"\nDjango settings for autocusto project.\nGenerated by 'django-admin startproject' using Django 2.2.6.\nFor more information on this file, see\nhttps://docs.djangoproject.com/en/2.2/topics/settings/\nFor the full list of settings and their values, see\nhttps://docs.djangoproject.com/en/2.2/ref/settings/\n"
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SECRET_KEY = '4(=4rbnajm+=ce3)99i9r8t3jqucv@hc(a&pum25qnc)ff@51x'
DEBUG = True
ALLOWED_HOSTS = ['localhost', '0.0.0.0', 'autocusto.com.br', 'www.autocusto.com.br']
SERVER = os.environ.get('SERVER')
INSTALLED_APPS = ['processos.apps.ProcessosConfig', 'medicos.apps.MedicosConfig', 'clinicas.apps.ClinicasConfig', 'pacientes.apps.PacientesConfig', 'usuarios.apps.UsuariosConfig', 'crispy_forms', 'django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles']
MIDDLEWARE = ['django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware']
ROOT_URLCONF = 'autocusto.urls'
TEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': [os.path.join(BASE_DIR, 'templates')], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}}]
WSGI_APPLICATION = 'autocusto.wsgi.application'
DATABASES = {'default': {'ENGINE': os.environ.get('SQL_ENGINE', 'django.db.backends.sqlite3'), 'NAME': os.environ.get('SQL_DATABASE', os.path.join(BASE_DIR, 'db.sqlite3')), 'USER': os.environ.get('SQL_USER', 'user'), 'PASSWORD': os.environ.get('SQL_PASSWORD', 'password'), 'HOST': os.environ.get('SQL_HOST', 'localhost'), 'PORT': os.environ.get('SQL_PORT', '5432')}}
AUTH_USER_MODEL = 'usuarios.Usuario'
AUTH_PASSWORD_VALIDATORS = [{'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'}, {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'}, {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'}, {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'}]
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'autocusto/static'), os.path.join(BASE_DIR, 'processos/static'), os.path.join(BASE_DIR, 'static')]
CRISPY_TEMPLATE_PACK = 'bootstrap4'
LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'
LME_BASE_PATH = os.path.join(BASE_DIR, 'processos/static/processos', 'lme_base_modelo.pdf')
PATH_REPORT = os.path.join(BASE_DIR, 'processos/static/processos', 'relatorio_modelo.pdf')
EXAMS_PATH = os.path.join(BASE_DIR, 'processos/static/processos', 'sadt.pdf')
PDF_DIR_PATH = os.path.join(BASE_DIR, 'processos/static/protocolos')
