
LME_BASE_PATH = 'modelos_pdf/lme_base_modelo.pdf'
EXAMS_PATH = 'modelos_pdf/exames_base_modelo.pdf'
PATH_REPORT = 'modelos_pdf/relatorio_modelo.pdf'
RCE_PATH = 'modelos_pdf/rce_modelo.pdf'
REPORT_AR_PATH = 'modelos_pdf/artrite_reumatoide/relatorio_modelo.pdf'
PATH_AR_CONSENT = 'modelos_pdf/artrite_reumatoide/consentimento_modelo.pdf'
MEEM_PATH = 'modelos_pdf/alzheimer/meem_modelo.pdf'
CDR_PATH = 'modelos_pdf/alzheimer/cdr_modelo.pdf'
CONSENT_PATH = 'modelos_pdf/alzheimer/consentimento_modelo.pdf'
PATH_EDSS = 'modelos_pdf/esclerose_multipla/edss_modelo.pdf'
EM_CONSENT_PATH = 'modelos_pdf/esclerose_multipla/consentimento.pdf'
FINGOLIMOD_MONITORING_PATH = 'modelos_pdf/esclerose_multipla/monitoramento_fingolimode_modelo.pdf'
NATA_EXAMS_PATH = 'modelos_pdf/esclerose_multipla/exames_nata_modelo.pdf'
EPILEPSY_CONSENT_PATH = 'modelos_pdf/epilepsia/consentimento_g400.pdf'
DISLIPIDEMIA_CONSENT_PATH = 'modelos_pdf/dislipidemia/consentimento_modelo.pdf'
PATH_DOR_CONSENTIMENTO = 'modelos_pdf/dor/consentimento_modelo.pdf'
PAIN_SCALE_PATH = 'modelos_pdf/dor/escala_modelo.pdf'
