# Generated by Django 5.2.4 on 2025-07-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='process_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Processos Criados'),
        ),
    ]
