# Generated by Django 3.0 on 2019-12-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_clinica', models.CharField(max_length=200)),
                ('cns_clinica', models.CharField(max_length=6)),
                ('end_clinica', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=9)),
                ('telefone_clinica', models.CharField(max_length=13)),
            ],
        ),
    ]
