# Generated by Django 3.0 on 2019-12-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicas',
            name='cep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clinicas',
            name='cns',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clinicas',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
