# Generated by Django 3.0 on 2019-12-12 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='medicos',
            field=models.ManyToManyField(related_name='clinica', to=settings.AUTH_USER_MODEL),
        ),
    ]
