# Generated by Django 3.0 on 2019-12-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='medicos',
            field=models.ManyToManyField(related_name='clinica', to='medicos.Medico'),
        ),
    ]
