# Generated by Django 3.0 on 2019-12-19 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0001_initial'),
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissor',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.Medico'),
        ),
        migrations.AddField(
            model_name='emissor',
            name='pacientes',
            field=models.ManyToManyField(related_name='emissores', through='processos.Processo', to='pacientes.Paciente'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='medicos',
            field=models.ManyToManyField(related_name='clinicas', through='clinicas.Emissor', to='medicos.Medico'),
        ),
    ]
