# Generated by Django 3.0 on 2019-12-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_auto_20191209_1337'),
        ('clinicas', '0002_auto_20191209_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cns', models.CharField(max_length=30)),
                ('end', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
                ('medico', models.ManyToManyField(to='medicos.Medico')),
            ],
        ),
        migrations.DeleteModel(
            name='Clinicas',
        ),
    ]
