# Generated by Django 3.0 on 2019-12-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0003_clinica_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissor',
            name='pacientes',
        ),
    ]
