# Generated by Django 3.0 on 2019-12-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0003_clinica_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='cns_clinica',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
