# Generated by Django 3.0 on 2020-02-03 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        ('clinicas', '0003_auto_20200203_0419'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicausuario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinica',
            name='medicos',
            field=models.ManyToManyField(related_name='clinicas', through='clinicas.Emissor', to='medicos.Medico'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='usuarios',
            field=models.ManyToManyField(related_name='clinicas', through='clinicas.ClinicaUsuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
