# Generated by Django 3.0 on 2019-12-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0003_auto_20191209_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinica',
            old_name='medico',
            new_name='medicos',
        ),
    ]
