# Generated by Django 3.0 on 2019-12-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_auto_20191209_1337'),
        ('clinicas', '0004_auto_20191209_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='medicos',
            field=models.ManyToManyField(related_name='clinicas', to='medicos.Medico'),
        ),
    ]
