# Generated by Django 3.0 on 2019-12-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0004_auto_20191217_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
    ]
