# Generated by Django 3.0 on 2019-12-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20191219_2301'),
        ('pacientes', '0003_auto_20191219_2302'),
        ('clinicas', '0004_remove_emissor_pacientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissor',
            name='pacientes',
            field=models.ManyToManyField(related_name='emissores', through='processos.Processo', to='pacientes.Paciente'),
        ),
    ]
