# Generated by Django 3.0.1 on 2020-01-29 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicas', '0004_auto_20200106_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='usuarios',
            field=models.ManyToManyField(related_name='clinicas', through='clinicas.ClinicaUsuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
