# Generated by Django 5.2rc1 on 2025-07-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicas", "0005_alter_clinica_id_alter_clinicausuario_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinica",
            name="telefone_clinica",
            field=models.CharField(max_length=15),
        ),
    ]
