# Generated by Django 3.0 on 2019-12-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0005_emissor_pacientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinica',
            old_name='end_clinica',
            new_name='logradouro',
        ),
        migrations.AddField(
            model_name='clinica',
            name='logradouro_num',
            field=models.CharField(default='string', max_length=6),
            preserve_default=False,
        ),
    ]
