# Generated by Django 5.2.4 on 2025-07-25 02:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicas", "0006_alter_clinica_telefone_clinica"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicaVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_clinica", models.CharField(max_length=200)),
                ("logradouro", models.CharField(max_length=200)),
                ("logradouro_num", models.CharField(max_length=6)),
                ("cidade", models.CharField(max_length=30)),
                ("bairro", models.CharField(max_length=30)),
                ("cep", models.CharField(max_length=9)),
                ("telefone_clinica", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("version_number", models.IntegerField()),
                (
                    "change_summary",
                    models.TextField(
                        blank=True, help_text="Summary of changes in this version"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("active", "Ativo"),
                            ("archived", "Arquivado"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="clinicas.clinica",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinic_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão da Clínica",
                "verbose_name_plural": "Versões das Clínicas",
                "ordering": ["-version_number", "-created_at"],
                "unique_together": {("clinica", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="ClinicaUsuarioVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "clinica_usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_version",
                        to="clinicas.clinicausuario",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_assignments",
                        to="clinicas.clinicaversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão Ativa do Usuário",
                "verbose_name_plural": "Versões Ativas dos Usuários",
            },
        ),
    ]
