# Generated by Django 3.0 on 2019-12-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0006_auto_20191220_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='cns_clinica',
            field=models.CharField(max_length=7),
        ),
    ]
