# Generated by Django 3.0 on 2019-12-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0006_auto_20191209_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
