# Generated by Django 3.0 on 2019-12-21 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicas', '0007_auto_20191221_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinica',
            name='usuario',
        ),
        migrations.CreateModel(
            name='ClinicaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicas.Clinica')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clinica',
            name='usuario',
            field=models.ManyToManyField(through='clinicas.ClinicaUsuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
