# Generated by Django 5.2.4 on 2025-07-25 02:16

from django.db import migrations


def create_initial_versions(apps, schema_editor):
    """Create initial versions for all existing clinics"""
    Clinica = apps.get_model('clinicas', 'Clinica')
    ClinicaVersion = apps.get_model('clinicas', 'ClinicaVersion')
    ClinicaUsuario = apps.get_model('clinicas', 'ClinicaUsuario')
    ClinicaUsuarioVersion = apps.get_model('clinicas', 'ClinicaUsuarioVersion')
    
    for clinica in Clinica.objects.all():
        # Create version 1 from existing clinic data
        version = ClinicaVersion.objects.create(
            clinica=clinica,
            nome_clinica=clinica.nome_clinica,
            logradouro=clinica.logradouro,
            logradouro_num=clinica.logradouro_num,
            cidade=clinica.cidade,
            bairro=clinica.bairro,
            cep=clinica.cep,
            telefone_clinica=clinica.telefone_clinica,
            created_by=None,  # System-created
            version_number=1,
            status='active',
            change_summary='Migração inicial - dados originais da clínica'
        )
        
        # Assign this version to all users connected to this clinic
        for clinica_usuario in ClinicaUsuario.objects.filter(clinica=clinica):
            ClinicaUsuarioVersion.objects.create(
                clinica_usuario=clinica_usuario,
                version=version
            )


def reverse_initial_versions(apps, schema_editor):
    """Reverse the initial version creation"""
    ClinicaUsuarioVersion = apps.get_model('clinicas', 'ClinicaUsuarioVersion')
    ClinicaVersion = apps.get_model('clinicas', 'ClinicaVersion')
    
    ClinicaUsuarioVersion.objects.all().delete()
    ClinicaVersion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0007_clinicaversion_clinicausuarioversion'),
    ]

    operations = [
        migrations.RunPython(create_initial_versions, reverse_initial_versions),
    ]
