# Generated by Django 5.2.4 on 2025-07-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0008_add_initial_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='cns_clinica',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
