# Generated by Django 5.2.4 on 2025-07-25 03:15

from django.db import migrations


def create_initial_user_versions(apps, schema_editor):
    """
    Create initial versions for all existing clinic-user relationships.
    
    For each ClinicaUsuario relationship that doesn't have a ClinicaUsuarioVersion,
    create an initial version using the master clinic data.
    """
    Clinica = apps.get_model('clinicas', 'Clinica')
    ClinicaVersion = apps.get_model('clinicas', 'ClinicaVersion')
    ClinicaUsuario = apps.get_model('clinicas', 'ClinicaUsuario')
    ClinicaUsuarioVersion = apps.get_model('clinicas', 'ClinicaUsuarioVersion')
    
    # Find all clinic-user relationships that don't have a version assigned
    clinic_users_without_versions = ClinicaUsuario.objects.filter(
        active_version__isnull=True
    ).select_related('clinica', 'usuario')
    
    print(f"Found {clinic_users_without_versions.count()} clinic-user relationships without versions")
    
    for clinic_user in clinic_users_without_versions:
        clinica = clinic_user.clinica
        usuario = clinic_user.usuario
        
        if not clinica or not usuario:
            continue
            
        # Check if this clinic already has versions
        existing_version = ClinicaVersion.objects.filter(clinica=clinica).first()
        
        if existing_version:
            # Clinic already has versions, assign the latest active one to this user
            latest_version = ClinicaVersion.objects.filter(
                clinica=clinica,
                status='active'
            ).order_by('-version_number').first()
            
            if latest_version:
                ClinicaUsuarioVersion.objects.create(
                    clinica_usuario=clinic_user,
                    version=latest_version
                )
                print(f"Assigned existing version {latest_version.version_number} to user {usuario.email} for clinic {clinica.nome_clinica}")
        else:
            # Clinic has no versions yet, create initial version from master data
            initial_version = ClinicaVersion.objects.create(
                clinica=clinica,
                version_number=1,
                created_by=usuario,
                status='active',
                nome_clinica=clinica.nome_clinica,
                logradouro=clinica.logradouro,
                logradouro_num=clinica.logradouro_num,
                cidade=clinica.cidade,
                bairro=clinica.bairro,
                cep=clinica.cep,
                telefone_clinica=clinica.telefone_clinica,
                change_summary='Versão inicial criada durante migração'
            )
            
            # Assign this version to the user
            ClinicaUsuarioVersion.objects.create(
                clinica_usuario=clinic_user,
                version=initial_version
            )
            print(f"Created initial version for user {usuario.email} for clinic {clinica.nome_clinica}")


def reverse_initial_user_versions(apps, schema_editor):
    """
    Remove all ClinicaUsuarioVersion relationships created by this migration.
    """
    ClinicaUsuarioVersion = apps.get_model('clinicas', 'ClinicaUsuarioVersion')
    ClinicaVersion = apps.get_model('clinicas', 'ClinicaVersion')
    
    # Remove version assignments
    ClinicaUsuarioVersion.objects.all().delete()
    
    # Remove versions created during migration (those with change_summary containing 'migração')
    ClinicaVersion.objects.filter(
        change_summary__icontains='migração'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0009_add_cns_unique_constraint'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_user_versions,
            reverse_initial_user_versions
        ),
    ]
