# Generated by Django 5.2.4 on 2025-07-26 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicas", "0010_create_initial_user_versions"),
        ("medicos", "0006_add_performance_indexes"),
        ("pacientes", "0005_create_initial_patient_versions"),
        ("processos", "0004_alter_processo_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="clinicausuario",
            index=models.Index(fields=["usuario"], name="clinicausuario_usuario_idx"),
        ),
        migrations.AddIndex(
            model_name="clinicausuario",
            index=models.Index(fields=["clinica"], name="clinicausuario_clinica_idx"),
        ),
        migrations.AddIndex(
            model_name="emissor",
            index=models.Index(
                fields=["medico", "clinica"], name="emissor_medico_clinica_idx"
            ),
        ),
    ]
